# -*- coding: utf-8 -*-
"""Birthday_Calculator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dtPZoBVsTqpPFOBacpNa_AKkDB-zPje8
"""

import datetime
#pip install emoji
#import emoji

"""*import a module named datetime to work with dates as date objects.*"""

current_date=datetime.date.today().strftime("%Y-%m-%d")
current_date_extract=current_date.split("-")

"""*we use the date.today() method to get the current local date.*

*We can use the strftime() method to create a string representing date in different formats.*

*Split the date as list separated by "-" using **split()** method.*
"""

bday_input=input("Enter you birthday in \"YYYY-mm-dd\" format:")
legend=input("Name of the birthday boy/girl ")
bday_date=bday_input.split("-")

"""*Enter you birthday date in the **"Year-month-day"** format*

*Input the name of the person whose b'day you want to check*

*Extract the bday date in terms of date,month & year using **split**()*
"""

if current_date_extract[1]==bday_date[1] and current_date_extract[2]==bday_date[2]:
  age=int(current_date_extract[0])-int(bday_date[0])
  print("Happy Birthday \U0001F389 dear",legend,"You have turned",age,"years old today")
  print("\U0001F929")
else:
  print("OOPS!! it's not your bday today dear")

"""*1)First check if their b'day month and date matches the current month and date*

*2)If yes, then calculate the age using current year and year you were born in else print a sorry message saying it's not their b'day*

*3)Finally print a b'day message with emojis and mentioning the name and age of the person*

*4)You can either use the  **emoji module** in python* 
"""